adback_db:
  image: mysql:5.7
  volumes:
   - ./db_data:/var/lib/mysql
  environment:
   MYSQL_ROOT_PASSWORD: drupal
   MYSQL_DATABASE: drupal
   MYSQL_USER: drupal
   MYSQL_PASSWORD: drupal
  ports:
   - "3308:3306"

drupal:
  links:
   - adback_db
  image: drupal:latest
  ports:
   - "80:80"
